// <auto-generated />
using System;
using GestaoAutomotiva.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoAutomotiva.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808154900_InitPg")]
    partial class InitPg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoAutomotiva.Models.AcessoriosCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CambioId")
                        .HasColumnType("integer");

                    b.Property<int>("CapotaId")
                        .HasColumnType("integer");

                    b.Property<int>("CarroceriaId")
                        .HasColumnType("integer");

                    b.Property<int>("EscapamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("ModeloId")
                        .HasColumnType("integer");

                    b.Property<int?>("MotorId")
                        .HasColumnType("integer");

                    b.Property<int>("PainelId")
                        .HasColumnType("integer");

                    b.Property<int>("PneuId")
                        .HasColumnType("integer");

                    b.Property<int>("RodaId")
                        .HasColumnType("integer");

                    b.Property<int>("SantoAntonioId")
                        .HasColumnType("integer");

                    b.Property<int>("SuspensaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CambioId");

                    b.HasIndex("CapotaId");

                    b.HasIndex("CarroceriaId");

                    b.HasIndex("EscapamentoId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("MotorId");

                    b.HasIndex("PainelId");

                    b.HasIndex("PneuId");

                    b.HasIndex("RodaId");

                    b.HasIndex("SantoAntonioId");

                    b.HasIndex("SuspensaoId");

                    b.ToTable("AcessoriosCarros");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarroId")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimativaDias")
                        .HasColumnType("integer");

                    b.Property<int?>("EtapaId")
                        .HasColumnType("integer");

                    b.Property<int?>("EtapaId1")
                        .HasColumnType("integer");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.HasIndex("EtapaId");

                    b.HasIndex("EtapaId1");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.AtividadeHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<string>("CarroId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EtapaAtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuncionarioNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeloNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("ServicoDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AtividadeHistoricos");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Cambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Cambios");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Capota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Capotas");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcessoriosCarroId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdCarro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModeloId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoManutencao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcessoriosCarroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Carroceria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Carrocerias");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Escapamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Escapamentos");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Etapas");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "FURLAN GT40"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "FURLAN COBRA"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "FURLAN SSK1929"
                        });
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroMotor")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("PlacaVeiculoDoador")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Almoxarifado")
                        .HasColumnType("text");

                    b.Property<int?>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CarroId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EtapaAtual")
                        .HasColumnType("text");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Inspetor")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .HasColumnType("text");

                    b.Property<string>("Tarefas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.ToTable("OrdemServicos");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Painel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Paineis");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Pneu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Pneus");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Roda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Rodas");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.SantoAntonio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("SantoAntonios");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimativaDias")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Suspensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Suspensaos");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gestao.com",
                            Nome = "Administrador",
                            Senha = "admin123",
                            Tipo = "Admin"
                        });
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.AcessoriosCarro", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Cambio", "Cambio")
                        .WithMany()
                        .HasForeignKey("CambioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Capota", "Capota")
                        .WithMany()
                        .HasForeignKey("CapotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Carroceria", "Carroceria")
                        .WithMany()
                        .HasForeignKey("CarroceriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Escapamento", "Escapamento")
                        .WithMany()
                        .HasForeignKey("EscapamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Motor", "Motor")
                        .WithMany()
                        .HasForeignKey("MotorId");

                    b.HasOne("GestaoAutomotiva.Models.Painel", "Painel")
                        .WithMany()
                        .HasForeignKey("PainelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Pneu", "Pneu")
                        .WithMany()
                        .HasForeignKey("PneuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Roda", "Roda")
                        .WithMany()
                        .HasForeignKey("RodaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.SantoAntonio", "SantoAntonio")
                        .WithMany()
                        .HasForeignKey("SantoAntonioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Suspensao", "Suspensao")
                        .WithMany()
                        .HasForeignKey("SuspensaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cambio");

                    b.Navigation("Capota");

                    b.Navigation("Carroceria");

                    b.Navigation("Escapamento");

                    b.Navigation("Modelo");

                    b.Navigation("Motor");

                    b.Navigation("Painel");

                    b.Navigation("Pneu");

                    b.Navigation("Roda");

                    b.Navigation("SantoAntonio");

                    b.Navigation("Suspensao");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Atividade", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestaoAutomotiva.Models.Etapa", null)
                        .WithMany("Atividades")
                        .HasForeignKey("EtapaId1");

                    b.HasOne("GestaoAutomotiva.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Etapa");

                    b.Navigation("Funcionario");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Cambio", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Cambios")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Capota", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Capotas")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Carro", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.AcessoriosCarro", "Acessorios")
                        .WithMany()
                        .HasForeignKey("AcessoriosCarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Cliente", "Cliente")
                        .WithMany("Carros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acessorios");

                    b.Navigation("Cliente");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Carroceria", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Carrocerias")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Escapamento", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Escapamentos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Motor", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Motores")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.OrdemServico", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Painel", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Paineis")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Pneu", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Roda", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.SantoAntonio", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Suspensao", b =>
                {
                    b.HasOne("GestaoAutomotiva.Models.Modelo", "Modelo")
                        .WithMany("Suspensoes")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Cliente", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Etapa", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("GestaoAutomotiva.Models.Modelo", b =>
                {
                    b.Navigation("Cambios");

                    b.Navigation("Capotas");

                    b.Navigation("Carrocerias");

                    b.Navigation("Escapamentos");

                    b.Navigation("Motores");

                    b.Navigation("Paineis");

                    b.Navigation("Suspensoes");
                });
#pragma warning restore 612, 618
        }
    }
}
